;;; hledger-rules-mode.el --- Major mode for hledger CSV rules files -*- lexical-binding: t; -*-

;; Copyright (C) 2026

;; Keywords: languages, data
;; Package-Requires: ((emacs "28.1"))

;;; Commentary:

;; A major mode for editing hledger CSV conversion rules (.rules files).
;; It provides:
;; - font-lock for directives, assignments, references, and matchers
;; - a lightweight parser-backed buffer index
;; - navigation, imenu, outline, completion, and eldoc
;; - internal flymake diagnostics
;; - commands for previewing rules and jumping to related files

;;; Code:

(require 'cl-lib)
(require 'compile)
(require 'eldoc)
(require 'flymake)
(require 'imenu)
(require 'outline)
(require 'project)
(require 'subr-x)

(defgroup hledger-rules nil
  "Editing hledger CSV rules files."
  :group 'languages)

(defcustom hledger-rules-indent-offset 2
  "Indentation width for assignments inside `if` blocks."
  :type 'integer
  :group 'hledger-rules)

(defcustom hledger-rules-hledger-program "hledger"
  "Program name used by hledger rules commands."
  :type 'string
  :group 'hledger-rules)

(defcustom hledger-rules-enable-flymake t
  "Whether to enable internal flymake diagnostics in `hledger-rules-mode'."
  :type 'boolean
  :group 'hledger-rules)

(defcustom hledger-rules-parse-delay 0.2
  "Idle time in seconds before reparsing the current buffer."
  :type 'number
  :group 'hledger-rules)

(defconst hledger-rules-directives
  '("source"
    "archive"
    "encoding"
    "date-format"
    "decimal-mark"
    "separator"
    "skip"
    "timezone"
    "newest-first"
    "intra-day-reversed"
    "balance-type")
  "Top-level directives accepted by hledger CSV rules files.")

(defconst hledger-rules-balance-types
  '("=" "=*" "==" "==*")
  "Valid balance assertion types.")

(defconst hledger-rules-journal-fields
  (let ((fields '("amount-in"
                  "amount-out"
                  "amount"
                  "balance"
                  "code"
                  "comment"
                  "currency"
                  "date2"
                  "date"
                  "description"
                  "status"
                  "skip"
                  "end")))
    (dotimes (idx 99)
      (let ((n (number-to-string (- 99 idx))))
        (setq fields
              (append
               (list (concat "account" n)
                     (concat "amount" n "-in")
                     (concat "amount" n "-out")
                     (concat "amount" n)
                     (concat "balance" n)
                     (concat "comment" n)
                     (concat "currency" n))
               fields))))
    fields)
  "hledger fields that can appear on the left-hand side of assignments.")

(defconst hledger-rules--directive-docs
  '(("source" . "Specify the input data file or a generator/cleaning command pipeline.")
    ("archive" . "Enable archiving of imported source files.")
    ("encoding" . "Declare the character encoding of the source data.")
    ("date-format" . "Declare the strptime format used for date/date-time fields.")
    ("decimal-mark" . "Declare the decimal mark used in ambiguous amount fields.")
    ("separator" . "Declare the source file field separator explicitly.")
    ("skip" . "Skip leading records at top level, or matching records inside an if block.")
    ("timezone" . "Specify the timezone for ambiguous date-times.")
    ("newest-first" . "Reverse same-date ordering when the file is newest-first.")
    ("intra-day-reversed" . "Reverse intra-day ordering relative to the main file order.")
    ("balance-type" . "Choose the balance assertion type generated by balance fields."))
  "Documentation strings for directives.")

(defconst hledger-rules--field-docs
  '(("date" . "Primary transaction date. A top-level date assignment is required.")
    ("date2" . "Secondary/posting date.")
    ("description" . "Transaction description/payee.")
    ("code" . "Transaction code.")
    ("status" . "Transaction status.")
    ("comment" . "Transaction comment.")
    ("comment1" . "Posting comment for posting 1.")
    ("comment2" . "Posting comment for posting 2.")
    ("amount" . "Transaction amount or posting amount, depending on context.")
    ("amount1" . "Posting amount for posting 1.")
    ("amount2" . "Posting amount for posting 2.")
    ("amount-in" . "Positive amount column.")
    ("amount-out" . "Negative amount column.")
    ("balance" . "Running balance assertion.")
    ("balance1" . "Running balance assertion for posting 1.")
    ("currency" . "Commodity/currency for the amount.")
    ("currency1" . "Commodity/currency for posting 1.")
    ("account1" . "First posting account.")
    ("account2" . "Second posting account.")
    ("skip" . "Inside an if block, skip the current record.")
    ("end" . "Inside an if block, skip all remaining records."))
  "Documentation strings for assignment fields.")

(cl-defstruct hledger-rules-directive
  name value beg end)

(cl-defstruct hledger-rules-fields
  names beg end raw)

(cl-defstruct hledger-rules-assignment
  lhs rhs beg end indented)

(cl-defstruct hledger-rules-include
  path beg end)

(cl-defstruct hledger-rules-block
  kind beg end header-beg header-end matchers assignments separator headers rows)

(cl-defstruct hledger-rules-parse-error
  beg end type message)

(cl-defstruct hledger-rules-index
  tick directives fields assignments blocks includes diagnostics top-level-items)

(defvar-local hledger-rules--index nil)
(defvar-local hledger-rules--parse-timer nil)
(defvar-local hledger-rules--dirty-p t)

(defconst hledger-rules--directive-regexp
  (concat "^\\([ \t]*\\)"
          (regexp-opt hledger-rules-directives t)
          "\\(?:\\(?::[ \t]*\\|[ \t]+\\)\\(.*\\)\\)?$"))

(defconst hledger-rules--assignment-lhs-regexp
  (regexp-opt hledger-rules-journal-fields t))

(defconst hledger-rules--assignment-regexp
  (concat "^\\(" hledger-rules--assignment-lhs-regexp
          "\\)\\(?:\\(?::[ \t]*\\|[ \t]+\\)\\(.*\\)\\)?$"))

(defconst hledger-rules--top-level-assignment-regexp
  (concat "^\\(" hledger-rules--assignment-lhs-regexp
          "\\)\\(?:\\(?::[ \t]*\\|[ \t]+\\)\\(.*\\)\\)?$"))

(defconst hledger-rules-font-lock-keywords
  `((,(concat "^[ \t]*\\(" (regexp-opt hledger-rules-directives t) "\\)\\>")
     1 font-lock-keyword-face)
    ("^[ \t]*\\(include\\)\\>" 1 font-lock-preprocessor-face)
    ("^[ \t]*\\(fields\\)\\>" 1 font-lock-keyword-face)
    (,(concat "^[ \t]*\\(" hledger-rules--assignment-lhs-regexp "\\)\\>")
     1 font-lock-variable-name-face)
    ("^[ \t]*\\(if\\)\\>" 1 font-lock-keyword-face)
    ("\\(?:^\\|[ \t]\\)\\(&&?\\|!\\)\\(?:[ \t]\\|$\\)" 1 font-lock-builtin-face)
    ("%([^) \t\n]+)" . font-lock-constant-face)
    ("%\"[^\"]+\"" . font-lock-constant-face)
    ("%[[:alnum:]_-]+" . font-lock-constant-face)
    ("\\\\[0-9]+" . font-lock-constant-face))
  "Font-lock expressions for `hledger-rules-mode'.")

(defvar hledger-rules-mode-map
  (let ((map (make-sparse-keymap)))
    (define-key map (kbd "C-c C-c") #'hledger-rules-preview-buffer)
    (define-key map (kbd "C-c C-d") #'hledger-rules-import-dry-run)
    (define-key map (kbd "C-c C-j") #'hledger-rules-jump-to-data-file)
    (define-key map (kbd "C-c C-o") #'hledger-rules-open-include)
    (define-key map (kbd "M-n") #'hledger-rules-next-rule)
    (define-key map (kbd "M-p") #'hledger-rules-previous-rule)
    map)
  "Keymap for `hledger-rules-mode'.")

(defun hledger-rules--comment-line-p (line)
  "Return non-nil if LINE is a comment line."
  (string-match-p "^[ \t]*[;#*]" line))

(defun hledger-rules--blank-line-p (line)
  "Return non-nil if LINE is blank."
  (string-match-p "^[ \t]*$" line))

(defun hledger-rules--trimmed-line ()
  "Return current line contents without text properties."
  (string-trim-right
   (buffer-substring-no-properties (line-beginning-position) (line-end-position))))

(defun hledger-rules--current-line-indented-p ()
  "Return non-nil if the current line starts with whitespace."
  (save-excursion
    (back-to-indentation)
    (> (current-column) 0)))

(defun hledger-rules--parse-fields-names (text)
  "Parse TEXT after a `fields` keyword into a list of field names."
  (let* ((body (replace-regexp-in-string "^fields\\(?::\\|[ \t]+\\)" "" text))
         (parts (split-string body "," nil))
         (names nil))
    (when (< (length parts) 2)
      (user-error "fields declarations require at least two comma-separated columns"))
    (dolist (part parts)
      (let ((name (string-trim part)))
        (push (downcase
               (if (and (> (length name) 1)
                        (string-prefix-p "\"" name)
                        (string-suffix-p "\"" name))
                   (substring name 1 -1)
                 name))
              names)))
    (nreverse names)))

(defun hledger-rules--parse-fields-line (line beg end diagnostics)
  "Parse a `fields` LINE spanning BEG to END.
Append any diagnostics to DIAGNOSTICS and return (FIELDS . DIAGNOSTICS)."
  (condition-case err
      (cons (make-hledger-rules-fields
             :names (hledger-rules--parse-fields-names line)
             :beg beg
             :end end
             :raw line)
            diagnostics)
    (error
     (cons nil
           (cons (make-hledger-rules-parse-error
                  :beg beg
                  :end end
                  :type :error
                  :message (error-message-string err))
                 diagnostics)))))

(defun hledger-rules--parse-assignment-from-string (text beg end &optional indented)
  "Parse assignment TEXT spanning BEG to END.
If INDENTED is non-nil, mark the assignment as indented."
  (when (string-match hledger-rules--assignment-regexp text)
    (make-hledger-rules-assignment
     :lhs (match-string 1 text)
     :rhs (or (match-string 2 text) "")
     :beg beg
     :end end
     :indented indented)))

(defun hledger-rules--implicit-assignments-from-fields (fields-item)
  "Return implicit top-level assignments induced by FIELDS-ITEM."
  (cl-loop for name in (hledger-rules-fields-names fields-item)
           unless (string-empty-p name)
           when (member name hledger-rules-journal-fields)
           collect (make-hledger-rules-assignment
                    :lhs name
                    :rhs (concat "%" name)
                    :beg (hledger-rules-fields-beg fields-item)
                    :end (hledger-rules-fields-end fields-item)
                    :indented nil)))

(defun hledger-rules--parse-directive-line (line beg end)
  "Parse directive LINE spanning BEG to END."
  (when (string-match hledger-rules--directive-regexp line)
    (make-hledger-rules-directive
     :name (match-string 2 line)
     :value (or (match-string 3 line) "")
     :beg beg
     :end end)))

(defun hledger-rules--parse-include-line (line beg end)
  "Parse include LINE spanning BEG to END."
  (when (string-match "^[ \t]*include[ \t]+\\(.+?\\)[ \t]*$" line)
    (make-hledger-rules-include
     :path (match-string 1 line)
     :beg beg
     :end end)))

(defun hledger-rules--parse-if-table (diagnostics)
  "Parse an `if` table at point and return (BLOCK DIAGNOSTICS NEXT-POS)."
  (let* ((header-beg (line-beginning-position))
         (header-end (line-end-position))
         (line (hledger-rules--trimmed-line))
         (sep (aref line 2))
         (body (substring line 3))
         (headers (split-string body (regexp-quote (string sep)) nil))
         (rows nil)
         (table-diags diagnostics))
    (forward-line 1)
    (while (and (not (eobp))
                (not (hledger-rules--blank-line-p (hledger-rules--trimmed-line))))
      (let* ((beg (line-beginning-position))
             (end (line-end-position))
             (row (hledger-rules--trimmed-line)))
        (unless (hledger-rules--comment-line-p row)
          (let* ((parts (split-string row (regexp-quote (string sep)) nil))
                 (matcher (car parts))
                 (values (cdr parts)))
            (if (/= (length values) (length headers))
                (push (make-hledger-rules-parse-error
                       :beg beg
                       :end end
                       :type :error
                       :message (format "if table row has %d value(s), expected %d"
                                        (length values) (length headers)))
                      table-diags)
              (push (list :beg beg :end end :matcher matcher :values values) rows)))))
      (forward-line 1))
    (let ((end-pos (if (eobp) (point-max) (line-end-position))))
      (unless (and headers (cl-every (lambda (header)
                                       (member header hledger-rules-journal-fields))
                                     headers))
        (push (make-hledger-rules-parse-error
               :beg header-beg
               :end header-end
               :type :error
               :message "if table header contains an unknown hledger field")
              table-diags))
      (unless rows
        (push (make-hledger-rules-parse-error
               :beg header-beg
               :end header-end
               :type :error
               :message "if table has no assignment rows")
              table-diags))
      (list
       (make-hledger-rules-block
        :kind 'table
        :beg header-beg
        :end end-pos
        :header-beg header-beg
        :header-end header-end
        :separator sep
        :headers headers
        :rows (nreverse rows))
       table-diags
       (if (eobp) (point-max) (1+ end-pos))))))

(defun hledger-rules--parse-if-block (diagnostics)
  "Parse an `if` block at point and return (BLOCK DIAGNOSTICS NEXT-POS)."
  (let* ((header-beg (line-beginning-position))
         (header-end (line-end-position))
         (line (hledger-rules--trimmed-line))
         (rest (string-trim (substring line 2)))
         (matchers (if (string-empty-p rest) nil (list rest)))
         (assignments nil)
         (block-diags diagnostics)
         (seen-body nil))
    (forward-line 1)
    (while (and (not (eobp))
                (not seen-body)
                (not (hledger-rules--blank-line-p (hledger-rules--trimmed-line))))
      (let ((current (hledger-rules--trimmed-line)))
        (cond
         ((hledger-rules--comment-line-p current)
          (forward-line 1))
         ((hledger-rules--current-line-indented-p)
          (setq seen-body t))
         (t
          (push current matchers)
          (forward-line 1)))))
    (while (and (not (eobp))
                (or (hledger-rules--current-line-indented-p)
                    (and seen-body (hledger-rules--blank-line-p (hledger-rules--trimmed-line)))))
      (let* ((beg (line-beginning-position))
             (end (line-end-position))
             (raw (buffer-substring-no-properties beg end))
             (trimmed (string-trim-left raw)))
        (cond
         ((hledger-rules--blank-line-p trimmed))
         ((hledger-rules--comment-line-p trimmed)
          (push (make-hledger-rules-parse-error
                 :beg beg
                 :end end
                 :type :warning
                 :message "comments inside if block bodies are not parsed specially")
                block-diags))
         (t
          (let ((assignment (hledger-rules--parse-assignment-from-string trimmed beg end t)))
            (if assignment
                (push assignment assignments)
              (push (make-hledger-rules-parse-error
                     :beg beg
                     :end end
                     :type :error
                     :message "expected an indented hledger field assignment")
                    block-diags)))))
        (forward-line 1)))
    (unless matchers
      (push (make-hledger-rules-parse-error
             :beg header-beg
             :end header-end
             :type :error
             :message "if block has no matchers")
            block-diags))
    (unless assignments
      (push (make-hledger-rules-parse-error
             :beg header-beg
             :end header-end
             :type :error
             :message "if block has no indented assignments")
            block-diags))
    (list
     (make-hledger-rules-block
      :kind 'block
      :beg header-beg
      :end (if (eobp) (point-max) (line-beginning-position))
      :header-beg header-beg
      :header-end header-end
      :matchers (nreverse matchers)
      :assignments (nreverse assignments))
     block-diags
     (point))))

(defun hledger-rules--parse-buffer ()
  "Parse the current buffer and return a `hledger-rules-index'."
  (save-excursion
    (save-restriction
      (widen)
      (goto-char (point-min))
      (let (directives fields assignments blocks includes diagnostics top-level-items)
        (while (not (eobp))
          (let* ((beg (line-beginning-position))
                 (end (line-end-position))
                 (line (hledger-rules--trimmed-line)))
            (cond
             ((or (hledger-rules--blank-line-p line)
                  (hledger-rules--comment-line-p line))
              (forward-line 1))
             ((string-match-p "^[ \t]*include\\>" line)
              (let ((include (hledger-rules--parse-include-line line beg end)))
                (when include
                  (push include includes)
                  (push (list :kind 'include :beg beg :label (hledger-rules-include-path include))
                        top-level-items)))
              (forward-line 1))
             ((string-match-p "^if[^[:alnum:][:space:]]" line)
              (pcase-let ((`(,block ,new-diags ,next-pos)
                           (hledger-rules--parse-if-table diagnostics)))
                (setq diagnostics new-diags)
                (push block blocks)
                (push (list :kind 'table
                            :beg (hledger-rules-block-beg block)
                            :label (format "if table %s"
                                           (string-join (hledger-rules-block-headers block) ", ")))
                      top-level-items)
                (goto-char next-pos)))
             ((string-match-p "^if\\(?:[ \t].*\\)?$" line)
              (pcase-let ((`(,block ,new-diags ,next-pos)
                           (hledger-rules--parse-if-block diagnostics)))
                (setq diagnostics new-diags)
                (push block blocks)
                (push (list :kind 'block
                            :beg (hledger-rules-block-beg block)
                            :label (format "if %s"
                                           (or (car (hledger-rules-block-matchers block)) "")))
                      top-level-items)
                (goto-char next-pos)))
             ((string-match-p "^[ \t]*fields\\(?::\\|[ \t]+\\)" line)
              (pcase-let ((`(,field ,new-diags)
                           (hledger-rules--parse-fields-line line beg end diagnostics)))
                (setq diagnostics new-diags)
                (when field
                  (push field fields)
                  (dolist (assignment (hledger-rules--implicit-assignments-from-fields field))
                    (push assignment assignments))
                  (push (list :kind 'fields :beg beg :label "fields") top-level-items)))
              (forward-line 1))
             ((and (not (string-match-p "^[ \t]" line))
                   (string-match hledger-rules--top-level-assignment-regexp line))
              (let ((assignment (hledger-rules--parse-assignment-from-string line beg end nil)))
                (push assignment assignments)
                (push (list :kind 'assignment
                            :beg beg
                            :label (hledger-rules-assignment-lhs assignment))
                      top-level-items)
                (when (and (string= (hledger-rules-assignment-lhs assignment) "balance-type")
                           (not (member (hledger-rules-assignment-rhs assignment)
                                        hledger-rules-balance-types)))
                  (push (make-hledger-rules-parse-error
                         :beg beg
                         :end end
                         :type :error
                         :message "balance-type must be one of =, =*, ==, ==*")
                        diagnostics)))
              (forward-line 1))
             ((let ((directive (and (not (string-match-p "^[ \t]" line))
                                    (hledger-rules--parse-directive-line line beg end))))
                (when directive
                  (push directive directives)
                  (push (list :kind 'directive
                              :beg beg
                              :label (hledger-rules-directive-name directive))
                        top-level-items)
                  (when (and (string= (hledger-rules-directive-name directive) "balance-type")
                             (not (member (hledger-rules-directive-value directive)
                                          hledger-rules-balance-types)))
                    (push (make-hledger-rules-parse-error
                           :beg beg
                           :end end
                           :type :error
                           :message "balance-type must be one of =, =*, ==, ==*")
                          diagnostics))
                  directive))
              (forward-line 1))
             ((string-match-p "^[ \t]+" line)
              (push (make-hledger-rules-parse-error
                     :beg beg
                     :end end
                     :type :warning
                     :message "indented line outside an if block")
                    diagnostics)
              (forward-line 1))
             (t
              (push (make-hledger-rules-parse-error
                     :beg beg
                     :end end
                     :type :warning
                     :message "unrecognized top-level rule")
                    diagnostics)
              (forward-line 1)))))
        (unless (cl-find-if (lambda (assignment)
                              (string= (hledger-rules-assignment-lhs assignment) "date"))
                            assignments)
          (push (make-hledger-rules-parse-error
                 :beg (point-min)
                 :end (point-min)
                 :type :error
                 :message "missing top-level date assignment")
                diagnostics))
        (make-hledger-rules-index
         :tick (buffer-chars-modified-tick)
         :directives (nreverse directives)
         :fields (nreverse fields)
         :assignments (nreverse assignments)
         :blocks (nreverse blocks)
         :includes (nreverse includes)
         :diagnostics (nreverse diagnostics)
         :top-level-items (sort (nreverse top-level-items)
                                (lambda (a b)
                                  (< (plist-get a :beg) (plist-get b :beg)))))))))

(defun hledger-rules--schedule-parse ()
  "Schedule a deferred parse of the current buffer."
  (when hledger-rules--parse-timer
    (cancel-timer hledger-rules--parse-timer))
  (setq hledger-rules--parse-timer
        (run-with-idle-timer
         hledger-rules-parse-delay
         nil
         (lambda (buffer)
           (when (buffer-live-p buffer)
             (with-current-buffer buffer
               (setq hledger-rules--index (hledger-rules--parse-buffer)
                     hledger-rules--dirty-p nil)
               (when hledger-rules-enable-flymake
                 (flymake-start)))))
         (current-buffer))))

(defun hledger-rules--after-change (&rest _)
  "Mark the current buffer dirty and schedule a reparse."
  (setq hledger-rules--dirty-p t)
  (hledger-rules--schedule-parse))

(defun hledger-rules--ensure-index ()
  "Return a current parse index for the buffer."
  (when (or hledger-rules--dirty-p
            (null hledger-rules--index)
            (/= (hledger-rules-index-tick hledger-rules--index)
                (buffer-chars-modified-tick)))
    (setq hledger-rules--index (hledger-rules--parse-buffer)
          hledger-rules--dirty-p nil))
  hledger-rules--index)

(defun hledger-rules--fields-before-point ()
  "Return the nearest declared CSV field list before point, or nil."
  (let* ((index (hledger-rules--ensure-index))
         (pos (point)))
    (cl-loop for item in (hledger-rules-index-fields index)
             when (<= (hledger-rules-fields-beg item) pos)
             maximize (hledger-rules-fields-beg item) into best-beg
             finally
             return (cl-find-if (lambda (it)
                                  (= (hledger-rules-fields-beg it) (or best-beg -1)))
                                (hledger-rules-index-fields index)))))

(defun hledger-rules--current-top-level-item ()
  "Return the top-level item at or before point."
  (let* ((index (hledger-rules--ensure-index))
         (pos (point)))
    (cl-loop for item in (hledger-rules-index-top-level-items index)
             if (<= (plist-get item :beg) pos)
             maximize (plist-get item :beg) into best-beg
             finally
             return (cl-find-if (lambda (it)
                                  (= (plist-get it :beg) (or best-beg -1)))
                                (hledger-rules-index-top-level-items index)))))

(defun hledger-rules-imenu-create-index ()
  "Build an imenu index from the current parse state."
  (let* ((index (hledger-rules--ensure-index))
         (entries nil))
    (dolist (item (hledger-rules-index-top-level-items index))
      (push (cons (plist-get item :label) (plist-get item :beg)) entries))
    (nreverse entries)))

(defun hledger-rules-next-rule ()
  "Jump to the next top-level rule."
  (interactive)
  (let* ((index (hledger-rules--ensure-index))
         (pos (point))
         (next (cl-find-if (lambda (item) (> (plist-get item :beg) pos))
                           (hledger-rules-index-top-level-items index))))
    (if next
        (goto-char (plist-get next :beg))
      (user-error "No next rule"))))

(defun hledger-rules-previous-rule ()
  "Jump to the previous top-level rule."
  (interactive)
  (let* ((index (hledger-rules--ensure-index))
         (pos (point))
         (items (reverse (hledger-rules-index-top-level-items index)))
         (prev (cl-find-if (lambda (item) (< (plist-get item :beg) pos)) items)))
    (if prev
        (goto-char (plist-get prev :beg))
      (user-error "No previous rule"))))

(defun hledger-rules-beginning-of-block ()
  "Jump to the beginning of the enclosing `if` block or table."
  (interactive)
  (let* ((index (hledger-rules--ensure-index))
         (pos (point))
         (block (cl-find-if (lambda (it)
                              (and (<= (hledger-rules-block-beg it) pos)
                                   (>= (hledger-rules-block-end it) pos)))
                            (hledger-rules-index-blocks index))))
    (if block
        (goto-char (hledger-rules-block-beg block))
      (user-error "Not inside an if block"))))

(defun hledger-rules-end-of-block ()
  "Jump to the end of the enclosing `if` block or table."
  (interactive)
  (let* ((index (hledger-rules--ensure-index))
         (pos (point))
         (block (cl-find-if (lambda (it)
                              (and (<= (hledger-rules-block-beg it) pos)
                                   (>= (hledger-rules-block-end it) pos)))
                            (hledger-rules-index-blocks index))))
    (if block
        (goto-char (hledger-rules-block-end block))
      (user-error "Not inside an if block"))))

(defun hledger-rules--previous-significant-line ()
  "Return the previous non-blank line as a cons of (INDENTED . TEXT), or nil."
  (save-excursion
    (catch 'found
      (while (zerop (forward-line -1))
        (let ((text (hledger-rules--trimmed-line)))
          (unless (hledger-rules--blank-line-p text)
            (throw 'found (cons (hledger-rules--current-line-indented-p) text)))))
      nil)))

(defun hledger-rules--indent-target ()
  "Return the indentation column appropriate for the current line."
  (let* ((trimmed (hledger-rules--trimmed-line))
         (trimmed-left (string-trim-left trimmed))
         (prev (hledger-rules--previous-significant-line)))
    (cond
     ((or (hledger-rules--blank-line-p trimmed)
          (hledger-rules--comment-line-p trimmed)
          (string-match-p "^if\\(?:[^[:alnum:][:space:]].*\\|\\(?:[ \t].*\\)?\\)$" trimmed)
          (string-match-p "^[ \t]*\\(?:include\\|fields\\)\\>" trimmed)
          (string-match-p hledger-rules--top-level-assignment-regexp trimmed)
          (string-match-p hledger-rules--directive-regexp trimmed))
      0)
     ((string-match-p hledger-rules--assignment-regexp trimmed-left)
      (if (and prev
               (or (string-match-p "^if\\(?:[ \t].*\\)?$" (cdr prev))
                   (car prev)))
          hledger-rules-indent-offset
        0))
     ((and prev
           (or (string-match-p "^if\\(?:[ \t].*\\)?$" (cdr prev))
               (car prev)))
      hledger-rules-indent-offset)
     (t 0))))

(defun hledger-rules-indent-line ()
  "Indent the current line as hledger CSV rules."
  (interactive)
  (let ((col (current-column))
        (indent (hledger-rules--indent-target)))
    (indent-line-to indent)
    (when (> col (current-column))
      (move-to-column col))))

(defun hledger-rules--capf-top-level-keyword ()
  "Completion for top-level keywords and assignment fields."
  (when (save-excursion
          (back-to-indentation)
          (= (point) (line-beginning-position)))
    (let ((bounds (bounds-of-thing-at-point 'symbol)))
      (when bounds
        (list (car bounds)
              (cdr bounds)
              (append hledger-rules-directives
                      '("fields" "include" "if")
                      hledger-rules-journal-fields)
              :exclusive 'no)))))

(defun hledger-rules--capf-balance-type ()
  "Completion for `balance-type` values."
  (save-excursion
    (back-to-indentation)
    (when (looking-at "balance-type\\(?:\\(?::\\|[ \t]+\\)\\(.*\\)\\)?$")
      (let ((value-beg (match-beginning 1))
            (value-end (match-end 1)))
        (when (and value-beg value-end
                   (<= value-beg (point))
                   (<= (point) value-end))
          (list value-beg value-end hledger-rules-balance-types))))))

(defun hledger-rules--capf-csv-field ()
  "Completion for CSV field references after `%`."
  (let ((pos (point))
        (fields-item (hledger-rules--fields-before-point)))
    (when fields-item
      (save-excursion
        (let ((start nil)
              (candidates (hledger-rules-fields-names fields-item)))
          (when (search-backward "%" (line-beginning-position) t)
            (setq start (1+ (point)))
            (when (or (= start pos)
                      (looking-at "%[[:alnum:]_-(]*"))
              (list start
                    pos
                    (append candidates
                            (mapcar #'number-to-string
                                    (number-sequence 1 (length candidates))))
                    :annotation-function
                    (lambda (candidate)
                      (if (string-match-p "^[0-9]+$" candidate) " [column]" " [field]"))
                    :exclusive 'no))))))))

(defun hledger-rules--capf-include-file ()
  "Completion for include targets."
  (save-excursion
    (back-to-indentation)
    (when (looking-at "include[ \t]+\\(.+\\)?")
      (let ((beg (or (match-beginning 1) (point)))
            (end (or (match-end 1) (point))))
        (when (<= beg (point))
          (list beg end #'completion-file-name-table
                :exclusive 'no))))))

(defun hledger-rules-capf ()
  "Completion-at-point function for `hledger-rules-mode'."
  (or (hledger-rules--capf-balance-type)
      (hledger-rules--capf-csv-field)
      (hledger-rules--capf-include-file)
      (hledger-rules--capf-top-level-keyword)))

(defun hledger-rules--field-reference-at-point ()
  "Return the CSV field reference near point, without the leading `%'."
  (save-excursion
    (let ((limit (line-beginning-position))
          (pos (point)))
      (when (search-backward "%" limit t)
        (let ((start (1+ (point))))
          (when (<= start pos)
            (buffer-substring-no-properties start pos)))))))

(defun hledger-rules-eldoc (callback &rest _ignored)
  "Return or report context-sensitive documentation using CALLBACK."
  (let* ((sym (thing-at-point 'symbol t))
         (fields-item (hledger-rules--fields-before-point))
         (ref (hledger-rules--field-reference-at-point))
         (doc
          (cond
           ((and sym (assoc sym hledger-rules--directive-docs))
            (cdr (assoc sym hledger-rules--directive-docs)))
           ((and sym (assoc sym hledger-rules--field-docs))
            (cdr (assoc sym hledger-rules--field-docs)))
           ((member (thing-at-point 'word t) hledger-rules-balance-types)
            "Valid balance-type values: =, =*, ==, ==*")
           ((and ref fields-item (string-match-p "^[0-9]+$" ref))
            (format "CSV column %s from current fields declaration" ref))
           ((and ref fields-item
                 (member (downcase ref) (hledger-rules-fields-names fields-item)))
            (format "CSV field `%s` from current fields declaration" ref))
           (t nil))))
    (when callback
      (funcall callback doc))
    doc))

(defun hledger-rules--line-diagnostics ()
  "Return internal diagnostics as flymake diagnostics."
  (let ((index (hledger-rules--ensure-index)))
    (mapcar
     (lambda (diag)
       (flymake-make-diagnostic
        (current-buffer)
        (hledger-rules-parse-error-beg diag)
        (max (hledger-rules-parse-error-beg diag)
             (hledger-rules-parse-error-end diag))
        (hledger-rules-parse-error-type diag)
        (hledger-rules-parse-error-message diag)))
     (hledger-rules-index-diagnostics index))))

(defun hledger-rules-flymake-backend (report-fn &rest _args)
  "Flymake backend for `hledger-rules-mode' using REPORT-FN."
  (funcall report-fn (if hledger-rules-enable-flymake
                         (hledger-rules--line-diagnostics)
                       nil)))

(defun hledger-rules--buffer-file-or-error ()
  "Return the current buffer file path, or raise a user error."
  (or buffer-file-name
      (user-error "This command requires a file-backed buffer")))

(defun hledger-rules--run-compilation (args)
  "Run `hledger-rules-hledger-program` with ARGS via `compilation-start`."
  (let ((command (mapconcat #'shell-quote-argument
                            (cons hledger-rules-hledger-program args)
                            " ")))
    (compilation-start command 'compilation-mode
                       (lambda (_mode) "*hledger rules*"))))

(defun hledger-rules-preview-buffer ()
  "Preview the current rules file by running `hledger print`."
  (interactive)
  (hledger-rules--run-compilation
   (list "-f" (hledger-rules--buffer-file-or-error) "print")))

(defun hledger-rules-import-dry-run ()
  "Run `hledger import --dry-run` on the current rules file."
  (interactive)
  (hledger-rules--run-compilation
   (list "import" (hledger-rules--buffer-file-or-error) "--dry-run")))

(defun hledger-rules--source-directive ()
  "Return the first `source` directive, or nil."
  (let ((index (hledger-rules--ensure-index)))
    (cl-find-if (lambda (directive)
                  (string= (hledger-rules-directive-name directive) "source"))
                (hledger-rules-index-directives index))))

(defun hledger-rules--resolve-associated-data-file ()
  "Resolve the associated source data file for the current rules file."
  (let* ((source (hledger-rules--source-directive))
         (rules-file (hledger-rules--buffer-file-or-error))
         (dir (file-name-directory rules-file)))
    (cond
     (source
      (let* ((value (string-trim (hledger-rules-directive-value source)))
             (path (car (split-string value "|" t "[ \t]+"))))
        (cond
         ((or (null path) (string-empty-p path)) nil)
         ((string-match-p "[[*?]" path)
          (car (sort (file-expand-wildcards (expand-file-name path dir) t)
                     #'file-newer-than-file-p)))
         (t (expand-file-name path dir)))))
     ((string-suffix-p ".rules" rules-file)
      (substring rules-file 0 (- (length rules-file) 6)))
     (t nil))))

(defun hledger-rules-jump-to-data-file ()
  "Open the associated source data file."
  (interactive)
  (let ((target (hledger-rules--resolve-associated-data-file)))
    (if (and target (file-exists-p target))
        (find-file target)
      (user-error "No associated data file found"))))

(defun hledger-rules-open-include ()
  "Open the include target on the current line."
  (interactive)
  (let* ((line (hledger-rules--trimmed-line))
         (rules-file (hledger-rules--buffer-file-or-error))
         (dir (file-name-directory rules-file)))
    (if (string-match "^[ \t]*include[ \t]+\\(.+?\\)[ \t]*$" line)
        (find-file (expand-file-name (match-string 1 line) dir))
      (user-error "Point is not on an include line"))))

(defun hledger-rules-show-fields ()
  "Show the nearest active CSV fields declaration."
  (interactive)
  (let ((fields-item (hledger-rules--fields-before-point)))
    (if fields-item
        (message "CSV fields: %s" (string-join (hledger-rules-fields-names fields-item) ", "))
      (user-error "No fields declaration found before point"))))

;;;###autoload
(define-derived-mode hledger-rules-mode prog-mode "Hledger-Rules"
  "Major mode for hledger CSV conversion rules."
  :group 'hledger-rules
  (setq-local font-lock-defaults '(hledger-rules-font-lock-keywords))
  (setq-local indent-line-function #'hledger-rules-indent-line)
  (setq-local comment-start "#")
  (setq-local comment-start-skip "^[ \t]*[;#*]+[ \t]*")
  (setq-local completion-at-point-functions '(hledger-rules-capf))
  (setq-local eldoc-documentation-functions '(hledger-rules-eldoc))
  (setq-local flymake-diagnostic-functions '(hledger-rules-flymake-backend))
  (setq-local imenu-create-index-function #'hledger-rules-imenu-create-index)
  (setq-local outline-regexp "^[ \t]*\\(?:if\\(?:[^[:alnum:][:space:]].*\\|\\(?:[ \t].*\\)?\\)\\|fields\\|include\\|source\\|archive\\|encoding\\|date-format\\|decimal-mark\\|separator\\|skip\\|timezone\\|newest-first\\|intra-day-reversed\\|balance-type\\)")
  (setq-local beginning-of-defun-function #'hledger-rules-beginning-of-block)
  (add-hook 'after-change-functions #'hledger-rules--after-change nil t)
  (setq hledger-rules--dirty-p t)
  (hledger-rules--ensure-index)
  (when hledger-rules-enable-flymake
    (flymake-mode 1)))

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.rules\\'" . hledger-rules-mode))

(provide 'hledger-rules-mode)

;;; hledger-rules-mode.el ends here
